### PR TITLE
Adding ability to provide cookies to youtube-dl

### PR DESCRIPTION
**Pull request by BorhnN**

### CODE REVIEW

**Comment by myrdd** [comment]
Some thoughts…
* How does youtube-dl behave with the `--download-archive` option *not* being used in case a video has been changed/updated?
* How should youtube-sync behave in this case? Should new versions be downloaded, and maybe the old version(s) preserved?  
iirc youtube-sync currently overwrites the old local video file in case the video has been updated.

IMHO these are important questions to think about. When I think about Web Archives (such as the wayback machine), or archives of VCS repos (such as the quite new [Software Heritage Archive](https://archive.softwareheritage.org/)), they all have the ability to store multiple versions of the same URL/URI. I would love such a multi-version feature in youtube-sync. When enabling `--download-archive`, however, new versions are ignored.

IMHO `--download-archive` option should be opt-in. What do you think @BorhnN?

**Comment by BorhnN** [comment]
> `--download-archive` option should be opt-in. What do you think @BorhnN?

I think just the same. In my application, `--download-archive` is ok. Because most of the youtube videos don't get updated. And when updated, they are often cropped. But that may not apply to everyone or every situation. (i.e. Syncing a channel as opposed to me syncing mostly `WL` playlist).

 Actually, I'm new to pull requests. Wanted to make two separate pull requests. But the commit was automatically included in the pr (I didn't expect it to). 

I'm reverting the commit now. Any thoughts on the COOKIES option? @myrdd @PotcFdk 

This was my first time working with bash too. Any way to improve syntax?

**Comment by myrdd** [comment]
> Any thoughts on the COOKIES option?

imho that's fine and a nice feature :)

> This was my first time working with bash too. Any way to improve syntax?

Let's see…

* @PotcFdk seems to use tabs, not spaces. You should convert the spaces back to tabs. (imho one should always go with spaces, but that's @PotcFdk's decision.)
* regards the `$COOKIE` variable, take a look at this Q&A: https://unix.stackexchange.com/questions/459367/using-shell-variables-for-command-options — basically use an array instead :)
* regarding ”global“ cookie files (`./cookies.txt`)… afaik currently the root only contains `SYNC/`, the channel dirs contain `ID/`, `LINK/` and `META/`. Would it make sense to create a root-level `META/` directory? So not `./cookies.txt` but `META/cookies.txt`?

regarding the `README.md` changes I suggest to link to the official youtube-dl FAQ instead, e.g. like this:

> To sync your private playlists […] you need a `cookies.txt` file, see [”How do I pass cookies to youtube-dl?“](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#user-content-how-do-i-pass-cookies-to-youtube-dl).

This way the step-by-step guide is maintained at the youtube-dl repo.

**Comment by PotcFdk** [comment]
Thanks! I might change it around at some point, but this seems to work as intended for now. :)

**Pull request merged**
